# Generated by Django 4.2 on 2024-01-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deezer_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('release_date', models.DateField()),
                ('cover', models.ImageField(unique=True, upload_to='')),
                ('genre', models.IntegerField(unique=True)),
                ('tracklist', models.URLField(unique=True)),
            ],
        ),
    ]
