# Generated by Django 4.2 on 2024-01-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deezer_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('link', models.URLField(max_length=255, unique=True)),
                ('image', models.ImageField(unique=True, upload_to='')),
                ('top_albums', models.ManyToManyField(to='album.album')),
            ],
        ),
    ]
