# Generated by Django 4.2 on 2024-01-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deezer_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('release_date', models.DateField()),
                ('preview', models.URLField(unique=True)),
                ('song_album', models.ManyToManyField(to='album.album')),
                ('song_artist', models.ManyToManyField(to='artist.artist')),
            ],
        ),
    ]
