# Generated by Django 4.2 on 2024-01-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_initial'),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_featured',
            field=models.ManyToManyField(related_name='featured', to='artist.artist'),
        ),
    ]
